-- FIX EVERYTHING SCRIPT
-- This script is idempotent (safe to run multiple times).
-- It ensures all tables, constraints, and policies exist and are correct.

-- 1. Create Tables (if missing)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  last_activity TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS daily_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  date DATE NOT NULL,
  questions_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS topic_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  topic_id TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  is_reviewed BOOLEAN DEFAULT FALSE,
  questions_total INTEGER DEFAULT 0,
  questions_correct INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS study_time (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    subject_id TEXT NOT NULL,
    seconds INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Add Unique Constraints (Safe way)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'daily_history_user_date_key') THEN
        ALTER TABLE daily_history ADD CONSTRAINT daily_history_user_date_key UNIQUE (user_id, date);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'topic_progress_user_topic_key') THEN
        ALTER TABLE topic_progress ADD CONSTRAINT topic_progress_user_topic_key UNIQUE (user_id, topic_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'study_time_user_subject_key') THEN
        ALTER TABLE study_time ADD CONSTRAINT study_time_user_subject_key UNIQUE (user_id, subject_id);
    END IF;
END $$;

-- 3. Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE topic_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_time ENABLE ROW LEVEL SECURITY;

-- 4. Re-create Policies (Drop first to avoid duplicates)
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;

DROP POLICY IF EXISTS "Users can view own history" ON daily_history;
DROP POLICY IF EXISTS "Users can update own history" ON daily_history;
DROP POLICY IF EXISTS "Users can insert own history" ON daily_history;

DROP POLICY IF EXISTS "Users can view own progress" ON topic_progress;
DROP POLICY IF EXISTS "Users can update own progress" ON topic_progress;
DROP POLICY IF EXISTS "Users can insert own progress" ON topic_progress;

DROP POLICY IF EXISTS "Users can view own study time" ON study_time;
DROP POLICY IF EXISTS "Users can update own study time" ON study_time;
DROP POLICY IF EXISTS "Users can insert own study time" ON study_time;

-- Create Policies
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can view own history" ON daily_history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own history" ON daily_history FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own history" ON daily_history FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own progress" ON topic_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own progress" ON topic_progress FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own progress" ON topic_progress FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own study time" ON study_time FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own study time" ON study_time FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own study time" ON study_time FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 5. Enable Realtime (Set tables safely - idempotent)
ALTER PUBLICATION supabase_realtime SET TABLE profiles, daily_history, topic_progress, study_time;
