-- DANGER: THIS WILL DELETE ALL DATA AND TABLES
-- Run this to completely reset the database schema.

-- 1. Drop Tables (Cascade deletes policies and triggers)
DROP TABLE IF EXISTS study_time CASCADE;
DROP TABLE IF EXISTS topic_progress CASCADE;
DROP TABLE IF EXISTS daily_history CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- 2. Re-create Tables
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  last_activity TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE daily_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  date DATE NOT NULL,
  questions_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, date)
);

CREATE TABLE topic_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  topic_id TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  is_reviewed BOOLEAN DEFAULT FALSE,
  questions_total INTEGER DEFAULT 0,
  questions_correct INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, topic_id)
);

CREATE TABLE study_time (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    subject_id TEXT NOT NULL,
    seconds INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, subject_id)
);

-- 3. Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE topic_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_time ENABLE ROW LEVEL SECURITY;

-- 4. Create Policies (Simple & Permissive for Owner)
-- Profiles
CREATE POLICY "Owner select profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Owner update profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Owner insert profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- Daily History
CREATE POLICY "Owner select history" ON daily_history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Owner update history" ON daily_history FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Owner insert history" ON daily_history FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Topic Progress
CREATE POLICY "Owner select progress" ON topic_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Owner update progress" ON topic_progress FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Owner insert progress" ON topic_progress FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Study Time
CREATE POLICY "Owner select time" ON study_time FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Owner update time" ON study_time FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Owner insert time" ON study_time FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 5. Enable Realtime
-- We use SET TABLE to force the configuration
ALTER PUBLICATION supabase_realtime SET TABLE profiles, daily_history, topic_progress, study_time;
