-- 1. Tabela de Perfis (Dados do Usuário)
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  xp integer default 0,
  level integer default 1,
  streak integer default 0,
  last_activity date
);

-- 2. Tabela de Histórico Diário (Para o Gráfico)
create table daily_history (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  questions_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Tabela de Progresso nos Tópicos
create table topic_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  topic_id text not null, -- ID do tópico como está no código (ex: 'civil-1')
  is_read boolean default false,
  is_reviewed boolean default false,
  questions_total integer default 0,
  questions_correct integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Tabela de Sessões de Estudo (Pomodoro)
create table study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  subject_id text not null,
  duration_seconds integer not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Habilitar segurança (RLS) para que cada usuário só veja seus dados
alter table profiles enable row level security;
alter table daily_history enable row level security;
alter table topic_progress enable row level security;
alter table study_sessions enable row level security;

-- Criar políticas de acesso (O usuário pode ver e editar suas próprias linhas)
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

create policy "Users can all on daily_history" on daily_history for all using (auth.uid() = user_id);
create policy "Users can all on topic_progress" on topic_progress for all using (auth.uid() = user_id);
create policy "Users can all on study_sessions" on study_sessions for all using (auth.uid() = user_id);

-- Função automática para criar perfil quando usuário se cadastra
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
