-- Create study_time table
CREATE TABLE IF NOT EXISTS study_time (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    subject_id TEXT NOT NULL,
    seconds INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, subject_id)
);

-- Enable RLS
ALTER TABLE study_time ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view own study time" ON study_time FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can update own study time" ON study_time FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own study time" ON study_time FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE study_time;
