-- SETUP NEW PROJECT SCRIPT
-- Run this in your NEW Supabase project's SQL Editor.

-- 1. Create Tables
CREATE TABLE profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  last_activity TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE daily_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  date DATE NOT NULL,
  questions_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, date)
);

CREATE TABLE topic_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  topic_id TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  is_reviewed BOOLEAN DEFAULT FALSE,
  questions_total INTEGER DEFAULT 0,
  questions_correct INTEGER DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, topic_id)
);

CREATE TABLE study_time (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    subject_id TEXT NOT NULL,
    seconds INTEGER DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, subject_id)
);

-- 2. Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE topic_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE study_time ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies (Owner Access Only)
CREATE POLICY "Owner select profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Owner update profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Owner insert profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Owner select history" ON daily_history FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Owner update history" ON daily_history FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Owner insert history" ON daily_history FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Owner select progress" ON topic_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Owner update progress" ON topic_progress FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Owner insert progress" ON topic_progress FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Owner select time" ON study_time FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Owner update time" ON study_time FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Owner insert time" ON study_time FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 4. Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE daily_history;
ALTER PUBLICATION supabase_realtime ADD TABLE topic_progress;
ALTER PUBLICATION supabase_realtime ADD TABLE study_time;
